opcion = input()
codigo1 = [11,12,3]

if opcion == "AGREGAR":
    codigo= input()
    codigo = int()
       
    producto1 = 'Melon'
    producto2 = "Maiz"
    producto3 = "Peras"
 
    precio1 = int(70)
    precio2 = 70000
    precio3 = 2700

    inventario1 = int(13)
    inventario2 = 1
    inventario3 = 33

    valor1 = 5588.2
    valor2 = 3504410.0

    if codigo in codigo1:
        print("Jamon","Melon", valor1, valor2 )
    else:
        print("nada")
    